# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/187z0JNB9v3ppwO1c0nuAFA6kkJ5kyGYD
"""

import streamlit as st
import numpy as np
import joblib

st.title("Predicción de Síndrome de Ovario Poliquístico (SOP)")
st.markdown("Completa los datos clínicos para predecir si una paciente presenta SOP.")

# Cargar modelo
modelo = joblib.load('modelo_sop.pkl')

# Entradas
edad = st.number_input("Edad", min_value=10, max_value=60, value=25)
bmi = st.number_input("IMC", min_value=10.0, max_value=60.0, value=25.0)
irregularidad = st.selectbox("¿Tiene irregularidad menstrual?", ["Sí", "No"])
testosterona = st.number_input("Testosterona (ng/dL)", min_value=0.0, max_value=200.0, value=50.0)
foliculos = st.number_input("Recuento de folículos antrales", min_value=0, max_value=50, value=20)

# Conversión
irregular = 1 if irregularidad == "Sí" else 0
entrada = np.array([[edad, bmi, irregular, testosterona, foliculos]])

if st.button("Predecir"):
    pred = modelo.predict(entrada)
    if pred[0] == 1:
        st.error("🔴 Diagnóstico Positivo de SOP")
    else:
        st.success("🟢 No hay SOP según el modelo")